
package org.tempuri;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "Exception", targetNamespace = "http://schemas.datacontract.org/2004/07/System")
public class FlightServiceShowFlightsByDepartureExceptionFaultFaultMessage
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private org.datacontract.schemas._2004._07.system.Exception faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public FlightServiceShowFlightsByDepartureExceptionFaultFaultMessage(String message, org.datacontract.schemas._2004._07.system.Exception faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public FlightServiceShowFlightsByDepartureExceptionFaultFaultMessage(String message, org.datacontract.schemas._2004._07.system.Exception faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.datacontract.schemas._2004._07.system.Exception
     */
    public org.datacontract.schemas._2004._07.system.Exception getFaultInfo() {
        return faultInfo;
    }

}
