//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI.TaxiService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaxiPriceInfoRequest", Namespace="http://schemas.datacontract.org/2004/07/ServicesDataContracts")]
    [System.SerializableAttribute()]
    public partial class TaxiPriceInfoRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AmountOfPassengersField;
        
        private System.DateTime DateTimeField;
        
        private GUI.TaxiService.Address DepartureAddressField;
        
        private GUI.TaxiService.Address DestinationAddressField;
        
        private bool IsDepartureTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int AmountOfPassengers {
            get {
                return this.AmountOfPassengersField;
            }
            set {
                if ((this.AmountOfPassengersField.Equals(value) != true)) {
                    this.AmountOfPassengersField = value;
                    this.RaisePropertyChanged("AmountOfPassengers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime DateTime {
            get {
                return this.DateTimeField;
            }
            set {
                if ((this.DateTimeField.Equals(value) != true)) {
                    this.DateTimeField = value;
                    this.RaisePropertyChanged("DateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public GUI.TaxiService.Address DepartureAddress {
            get {
                return this.DepartureAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartureAddressField, value) != true)) {
                    this.DepartureAddressField = value;
                    this.RaisePropertyChanged("DepartureAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public GUI.TaxiService.Address DestinationAddress {
            get {
                return this.DestinationAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinationAddressField, value) != true)) {
                    this.DestinationAddressField = value;
                    this.RaisePropertyChanged("DestinationAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool IsDepartureTime {
            get {
                return this.IsDepartureTimeField;
            }
            set {
                if ((this.IsDepartureTimeField.Equals(value) != true)) {
                    this.IsDepartureTimeField = value;
                    this.RaisePropertyChanged("IsDepartureTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class Address : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CityField;
        
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Number {
            get {
                return this.NumberField;
            }
            set {
                if ((this.NumberField.Equals(value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Street {
            get {
                return this.StreetField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetField, value) != true)) {
                    this.StreetField = value;
                    this.RaisePropertyChanged("Street");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode {
            get {
                return this.ZipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipCodeField, value) != true)) {
                    this.ZipCodeField = value;
                    this.RaisePropertyChanged("ZipCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaxiPriceInfo", Namespace="http://schemas.datacontract.org/2004/07/ServicesDataContracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GUI.TaxiService.TaxiBooking))]
    public partial class TaxiPriceInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AmountOfPassengersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GUI.TaxiService.Address DepartureAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GUI.TaxiService.Address DestinationAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDepartureTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TaxiIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TaxiTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AmountOfPassengers {
            get {
                return this.AmountOfPassengersField;
            }
            set {
                if ((this.AmountOfPassengersField.Equals(value) != true)) {
                    this.AmountOfPassengersField = value;
                    this.RaisePropertyChanged("AmountOfPassengers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTime {
            get {
                return this.DateTimeField;
            }
            set {
                if ((this.DateTimeField.Equals(value) != true)) {
                    this.DateTimeField = value;
                    this.RaisePropertyChanged("DateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GUI.TaxiService.Address DepartureAddress {
            get {
                return this.DepartureAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartureAddressField, value) != true)) {
                    this.DepartureAddressField = value;
                    this.RaisePropertyChanged("DepartureAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GUI.TaxiService.Address DestinationAddress {
            get {
                return this.DestinationAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinationAddressField, value) != true)) {
                    this.DestinationAddressField = value;
                    this.RaisePropertyChanged("DestinationAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDepartureTime {
            get {
                return this.IsDepartureTimeField;
            }
            set {
                if ((this.IsDepartureTimeField.Equals(value) != true)) {
                    this.IsDepartureTimeField = value;
                    this.RaisePropertyChanged("IsDepartureTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TaxiId {
            get {
                return this.TaxiIdField;
            }
            set {
                if ((this.TaxiIdField.Equals(value) != true)) {
                    this.TaxiIdField = value;
                    this.RaisePropertyChanged("TaxiId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaxiType {
            get {
                return this.TaxiTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TaxiTypeField, value) != true)) {
                    this.TaxiTypeField = value;
                    this.RaisePropertyChanged("TaxiType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaxiBooking", Namespace="http://schemas.datacontract.org/2004/07/ServicesDataContracts")]
    [System.SerializableAttribute()]
    public partial class TaxiBooking : GUI.TaxiService.TaxiPriceInfo {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserBookingsRequest", Namespace="http://schemas.datacontract.org/2004/07/ServicesDataContracts")]
    [System.SerializableAttribute()]
    public partial class UserBookingsRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BookingIdField;
        
        private string UserTokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BookingId {
            get {
                return this.BookingIdField;
            }
            set {
                if ((this.BookingIdField.Equals(value) != true)) {
                    this.BookingIdField = value;
                    this.RaisePropertyChanged("BookingId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string UserToken {
            get {
                return this.UserTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.UserTokenField, value) != true)) {
                    this.UserTokenField = value;
                    this.RaisePropertyChanged("UserToken");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserBookings", Namespace="http://schemas.datacontract.org/2004/07/ServicesDataContracts")]
    [System.SerializableAttribute()]
    public partial class UserBookings : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GUI.TaxiService.TaxiBooking[] TaxiBookingsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GUI.TaxiService.TaxiBooking[] TaxiBookings {
            get {
                return this.TaxiBookingsField;
            }
            set {
                if ((object.ReferenceEquals(this.TaxiBookingsField, value) != true)) {
                    this.TaxiBookingsField = value;
                    this.RaisePropertyChanged("TaxiBookings");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CancelBookingRequest", Namespace="http://schemas.datacontract.org/2004/07/ServicesDataContracts")]
    [System.SerializableAttribute()]
    public partial class CancelBookingRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int BookingIdField;
        
        private string UserTokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int BookingId {
            get {
                return this.BookingIdField;
            }
            set {
                if ((this.BookingIdField.Equals(value) != true)) {
                    this.BookingIdField = value;
                    this.RaisePropertyChanged("BookingId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string UserToken {
            get {
                return this.UserTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.UserTokenField, value) != true)) {
                    this.UserTokenField = value;
                    this.RaisePropertyChanged("UserToken");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetAddressRequest", Namespace="http://schemas.datacontract.org/2004/07/ServicesDataContracts")]
    [System.SerializableAttribute()]
    public partial class GetAddressRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string LocationNameField;
        
        private int LocationTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string LocationName {
            get {
                return this.LocationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationNameField, value) != true)) {
                    this.LocationNameField = value;
                    this.RaisePropertyChanged("LocationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int LocationType {
            get {
                return this.LocationTypeField;
            }
            set {
                if ((this.LocationTypeField.Equals(value) != true)) {
                    this.LocationTypeField = value;
                    this.RaisePropertyChanged("LocationType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TaxiService.ITaxiService")]
    public interface ITaxiService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxiService/GetTaxiPriceInfo", ReplyAction="http://tempuri.org/ITaxiService/GetTaxiPriceInfoResponse")]
        GUI.TaxiService.TaxiPriceInfo GetTaxiPriceInfo(GUI.TaxiService.TaxiPriceInfoRequest taxiPriceInfoRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxiService/GetTaxiPriceInfo", ReplyAction="http://tempuri.org/ITaxiService/GetTaxiPriceInfoResponse")]
        System.Threading.Tasks.Task<GUI.TaxiService.TaxiPriceInfo> GetTaxiPriceInfoAsync(GUI.TaxiService.TaxiPriceInfoRequest taxiPriceInfoRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxiService/DoTaxiBooking", ReplyAction="http://tempuri.org/ITaxiService/DoTaxiBookingResponse")]
        GUI.TaxiService.TaxiBooking DoTaxiBooking(GUI.TaxiService.TaxiPriceInfo taxiPriceInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxiService/DoTaxiBooking", ReplyAction="http://tempuri.org/ITaxiService/DoTaxiBookingResponse")]
        System.Threading.Tasks.Task<GUI.TaxiService.TaxiBooking> DoTaxiBookingAsync(GUI.TaxiService.TaxiPriceInfo taxiPriceInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxiService/GetUserBookings", ReplyAction="http://tempuri.org/ITaxiService/GetUserBookingsResponse")]
        GUI.TaxiService.UserBookings GetUserBookings(GUI.TaxiService.UserBookingsRequest userBookingsRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxiService/GetUserBookings", ReplyAction="http://tempuri.org/ITaxiService/GetUserBookingsResponse")]
        System.Threading.Tasks.Task<GUI.TaxiService.UserBookings> GetUserBookingsAsync(GUI.TaxiService.UserBookingsRequest userBookingsRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxiService/CancelBooking", ReplyAction="http://tempuri.org/ITaxiService/CancelBookingResponse")]
        bool CancelBooking(GUI.TaxiService.CancelBookingRequest cancelBookingRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxiService/CancelBooking", ReplyAction="http://tempuri.org/ITaxiService/CancelBookingResponse")]
        System.Threading.Tasks.Task<bool> CancelBookingAsync(GUI.TaxiService.CancelBookingRequest cancelBookingRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxiService/GetCitys", ReplyAction="http://tempuri.org/ITaxiService/GetCitysResponse")]
        string[] GetCitys(string country);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxiService/GetCitys", ReplyAction="http://tempuri.org/ITaxiService/GetCitysResponse")]
        System.Threading.Tasks.Task<string[]> GetCitysAsync(string country);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxiService/GetAddress", ReplyAction="http://tempuri.org/ITaxiService/GetAddressResponse")]
        string[] GetAddress(GUI.TaxiService.GetAddressRequest getAddressRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxiService/GetAddress", ReplyAction="http://tempuri.org/ITaxiService/GetAddressResponse")]
        System.Threading.Tasks.Task<string[]> GetAddressAsync(GUI.TaxiService.GetAddressRequest getAddressRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxiService/GetSpecialLocations", ReplyAction="http://tempuri.org/ITaxiService/GetSpecialLocationsResponse")]
        string[] GetSpecialLocations(string locationType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxiService/GetSpecialLocations", ReplyAction="http://tempuri.org/ITaxiService/GetSpecialLocationsResponse")]
        System.Threading.Tasks.Task<string[]> GetSpecialLocationsAsync(string locationType);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITaxiServiceChannel : GUI.TaxiService.ITaxiService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TaxiServiceClient : System.ServiceModel.ClientBase<GUI.TaxiService.ITaxiService>, GUI.TaxiService.ITaxiService {
        
        public TaxiServiceClient() {
        }
        
        public TaxiServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TaxiServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TaxiServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TaxiServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GUI.TaxiService.TaxiPriceInfo GetTaxiPriceInfo(GUI.TaxiService.TaxiPriceInfoRequest taxiPriceInfoRequest) {
            return base.Channel.GetTaxiPriceInfo(taxiPriceInfoRequest);
        }
        
        public System.Threading.Tasks.Task<GUI.TaxiService.TaxiPriceInfo> GetTaxiPriceInfoAsync(GUI.TaxiService.TaxiPriceInfoRequest taxiPriceInfoRequest) {
            return base.Channel.GetTaxiPriceInfoAsync(taxiPriceInfoRequest);
        }
        
        public GUI.TaxiService.TaxiBooking DoTaxiBooking(GUI.TaxiService.TaxiPriceInfo taxiPriceInfo) {
            return base.Channel.DoTaxiBooking(taxiPriceInfo);
        }
        
        public System.Threading.Tasks.Task<GUI.TaxiService.TaxiBooking> DoTaxiBookingAsync(GUI.TaxiService.TaxiPriceInfo taxiPriceInfo) {
            return base.Channel.DoTaxiBookingAsync(taxiPriceInfo);
        }
        
        public GUI.TaxiService.UserBookings GetUserBookings(GUI.TaxiService.UserBookingsRequest userBookingsRequest) {
            return base.Channel.GetUserBookings(userBookingsRequest);
        }
        
        public System.Threading.Tasks.Task<GUI.TaxiService.UserBookings> GetUserBookingsAsync(GUI.TaxiService.UserBookingsRequest userBookingsRequest) {
            return base.Channel.GetUserBookingsAsync(userBookingsRequest);
        }
        
        public bool CancelBooking(GUI.TaxiService.CancelBookingRequest cancelBookingRequest) {
            return base.Channel.CancelBooking(cancelBookingRequest);
        }
        
        public System.Threading.Tasks.Task<bool> CancelBookingAsync(GUI.TaxiService.CancelBookingRequest cancelBookingRequest) {
            return base.Channel.CancelBookingAsync(cancelBookingRequest);
        }
        
        public string[] GetCitys(string country) {
            return base.Channel.GetCitys(country);
        }
        
        public System.Threading.Tasks.Task<string[]> GetCitysAsync(string country) {
            return base.Channel.GetCitysAsync(country);
        }
        
        public string[] GetAddress(GUI.TaxiService.GetAddressRequest getAddressRequest) {
            return base.Channel.GetAddress(getAddressRequest);
        }
        
        public System.Threading.Tasks.Task<string[]> GetAddressAsync(GUI.TaxiService.GetAddressRequest getAddressRequest) {
            return base.Channel.GetAddressAsync(getAddressRequest);
        }
        
        public string[] GetSpecialLocations(string locationType) {
            return base.Channel.GetSpecialLocations(locationType);
        }
        
        public System.Threading.Tasks.Task<string[]> GetSpecialLocationsAsync(string locationType) {
            return base.Channel.GetSpecialLocationsAsync(locationType);
        }
    }
}
