//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxiClient.AttractionService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://booking/", ConfigurationName="AttractionService.AttractionImplementation")]
    public interface AttractionImplementation {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://booking/AttractionImplementation/getCountriesRequest", ReplyAction="http://booking/AttractionImplementation/getCountriesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TaxiClient.AttractionService.getCountriesResponse getCountries(TaxiClient.AttractionService.getCountriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://booking/AttractionImplementation/getCountriesRequest", ReplyAction="http://booking/AttractionImplementation/getCountriesResponse")]
        System.Threading.Tasks.Task<TaxiClient.AttractionService.getCountriesResponse> getCountriesAsync(TaxiClient.AttractionService.getCountriesRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://booking/AttractionImplementation/getRegionsRequest", ReplyAction="http://booking/AttractionImplementation/getRegionsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TaxiClient.AttractionService.getRegionsResponse getRegions(TaxiClient.AttractionService.getRegionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://booking/AttractionImplementation/getRegionsRequest", ReplyAction="http://booking/AttractionImplementation/getRegionsResponse")]
        System.Threading.Tasks.Task<TaxiClient.AttractionService.getRegionsResponse> getRegionsAsync(TaxiClient.AttractionService.getRegionsRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://booking/AttractionImplementation/getBookingRequest", ReplyAction="http://booking/AttractionImplementation/getBookingResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TaxiClient.AttractionService.getBookingResponse getBooking(TaxiClient.AttractionService.getBookingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://booking/AttractionImplementation/getBookingRequest", ReplyAction="http://booking/AttractionImplementation/getBookingResponse")]
        System.Threading.Tasks.Task<TaxiClient.AttractionService.getBookingResponse> getBookingAsync(TaxiClient.AttractionService.getBookingRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://booking/AttractionImplementation/getCitiesRequest", ReplyAction="http://booking/AttractionImplementation/getCitiesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TaxiClient.AttractionService.getCitiesResponse getCities(TaxiClient.AttractionService.getCitiesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://booking/AttractionImplementation/getCitiesRequest", ReplyAction="http://booking/AttractionImplementation/getCitiesResponse")]
        System.Threading.Tasks.Task<TaxiClient.AttractionService.getCitiesResponse> getCitiesAsync(TaxiClient.AttractionService.getCitiesRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://booking/AttractionImplementation/getAttractionsRequest", ReplyAction="http://booking/AttractionImplementation/getAttractionsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TaxiClient.AttractionService.getAttractionsResponse getAttractions(TaxiClient.AttractionService.getAttractionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://booking/AttractionImplementation/getAttractionsRequest", ReplyAction="http://booking/AttractionImplementation/getAttractionsResponse")]
        System.Threading.Tasks.Task<TaxiClient.AttractionService.getAttractionsResponse> getAttractionsAsync(TaxiClient.AttractionService.getAttractionsRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://booking/AttractionImplementation/bookAttractionRequest", ReplyAction="http://booking/AttractionImplementation/bookAttractionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TaxiClient.AttractionService.bookAttractionResponse bookAttraction(TaxiClient.AttractionService.bookAttractionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://booking/AttractionImplementation/bookAttractionRequest", ReplyAction="http://booking/AttractionImplementation/bookAttractionResponse")]
        System.Threading.Tasks.Task<TaxiClient.AttractionService.bookAttractionResponse> bookAttractionAsync(TaxiClient.AttractionService.bookAttractionRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://booking/AttractionImplementation/getAttractionTypesRequest", ReplyAction="http://booking/AttractionImplementation/getAttractionTypesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TaxiClient.AttractionService.getAttractionTypesResponse getAttractionTypes(TaxiClient.AttractionService.getAttractionTypesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://booking/AttractionImplementation/getAttractionTypesRequest", ReplyAction="http://booking/AttractionImplementation/getAttractionTypesResponse")]
        System.Threading.Tasks.Task<TaxiClient.AttractionService.getAttractionTypesResponse> getAttractionTypesAsync(TaxiClient.AttractionService.getAttractionTypesRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://booking/")]
    public partial class country : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string countryCodeField;
        
        private string countryNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string countryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
                this.RaisePropertyChanged("countryCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string countryName {
            get {
                return this.countryNameField;
            }
            set {
                this.countryNameField = value;
                this.RaisePropertyChanged("countryName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://booking/")]
    public partial class city : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int cityIDField;
        
        private string cityNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int cityID {
            get {
                return this.cityIDField;
            }
            set {
                this.cityIDField = value;
                this.RaisePropertyChanged("cityID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string cityName {
            get {
                return this.cityNameField;
            }
            set {
                this.cityNameField = value;
                this.RaisePropertyChanged("cityName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://booking/")]
    public partial class orderedTicket : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int ticketTypeIDField;
        
        private int amountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int ticketTypeID {
            get {
                return this.ticketTypeIDField;
            }
            set {
                this.ticketTypeIDField = value;
                this.RaisePropertyChanged("ticketTypeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("amount");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://booking/")]
    public partial class ticketType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descriptionField;
        
        private int idField;
        
        private double priceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("price");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://booking/")]
    public partial class attractieType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string attractionTypeNameField;
        
        private int attractionTypeIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string attractionTypeName {
            get {
                return this.attractionTypeNameField;
            }
            set {
                this.attractionTypeNameField = value;
                this.RaisePropertyChanged("attractionTypeName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int attractionTypeID {
            get {
                return this.attractionTypeIDField;
            }
            set {
                this.attractionTypeIDField = value;
                this.RaisePropertyChanged("attractionTypeID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://booking/")]
    public partial class attractie : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int attractionIDField;
        
        private string naamField;
        
        private string addressField;
        
        private string descriptionField;
        
        private string[] picturesField;
        
        private string websiteField;
        
        private attractieType attractionTypeField;
        
        private ticketType[] ticketsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int attractionID {
            get {
                return this.attractionIDField;
            }
            set {
                this.attractionIDField = value;
                this.RaisePropertyChanged("attractionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string naam {
            get {
                return this.naamField;
            }
            set {
                this.naamField = value;
                this.RaisePropertyChanged("naam");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pictures", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string[] pictures {
            get {
                return this.picturesField;
            }
            set {
                this.picturesField = value;
                this.RaisePropertyChanged("pictures");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string website {
            get {
                return this.websiteField;
            }
            set {
                this.websiteField = value;
                this.RaisePropertyChanged("website");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public attractieType attractionType {
            get {
                return this.attractionTypeField;
            }
            set {
                this.attractionTypeField = value;
                this.RaisePropertyChanged("attractionType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("tickets", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public ticketType[] tickets {
            get {
                return this.ticketsField;
            }
            set {
                this.ticketsField = value;
                this.RaisePropertyChanged("tickets");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://booking/")]
    public partial class booking : object, System.ComponentModel.INotifyPropertyChanged {
        
        private attractie attractionField;
        
        private orderedTicket[] orderedTicketsField;
        
        private double priceField;
        
        private string statusField;
        
        private System.DateTime datumField;
        
        private bool datumFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public attractie attraction {
            get {
                return this.attractionField;
            }
            set {
                this.attractionField = value;
                this.RaisePropertyChanged("attraction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("orderedTickets", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public orderedTicket[] orderedTickets {
            get {
                return this.orderedTicketsField;
            }
            set {
                this.orderedTicketsField = value;
                this.RaisePropertyChanged("orderedTickets");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime datum {
            get {
                return this.datumField;
            }
            set {
                this.datumField = value;
                this.RaisePropertyChanged("datum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool datumSpecified {
            get {
                return this.datumFieldSpecified;
            }
            set {
                this.datumFieldSpecified = value;
                this.RaisePropertyChanged("datumSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://booking/")]
    public partial class region : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int regionIDField;
        
        private string regionNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int regionID {
            get {
                return this.regionIDField;
            }
            set {
                this.regionIDField = value;
                this.RaisePropertyChanged("regionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string regionName {
            get {
                return this.regionNameField;
            }
            set {
                this.regionNameField = value;
                this.RaisePropertyChanged("regionName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCountries", WrapperNamespace="http://booking/", IsWrapped=true)]
    public partial class getCountriesRequest {
        
        public getCountriesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCountriesResponse", WrapperNamespace="http://booking/", IsWrapped=true)]
    public partial class getCountriesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://booking/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public TaxiClient.AttractionService.country[] @return;
        
        public getCountriesResponse() {
        }
        
        public getCountriesResponse(TaxiClient.AttractionService.country[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRegions", WrapperNamespace="http://booking/", IsWrapped=true)]
    public partial class getRegionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://booking/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public getRegionsRequest() {
        }
        
        public getRegionsRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRegionsResponse", WrapperNamespace="http://booking/", IsWrapped=true)]
    public partial class getRegionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://booking/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public TaxiClient.AttractionService.region[] @return;
        
        public getRegionsResponse() {
        }
        
        public getRegionsResponse(TaxiClient.AttractionService.region[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getBooking", WrapperNamespace="http://booking/", IsWrapped=true)]
    public partial class getBookingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://booking/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://booking/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public getBookingRequest() {
        }
        
        public getBookingRequest(int arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getBookingResponse", WrapperNamespace="http://booking/", IsWrapped=true)]
    public partial class getBookingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://booking/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public TaxiClient.AttractionService.booking[] @return;
        
        public getBookingResponse() {
        }
        
        public getBookingResponse(TaxiClient.AttractionService.booking[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCities", WrapperNamespace="http://booking/", IsWrapped=true)]
    public partial class getCitiesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://booking/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public getCitiesRequest() {
        }
        
        public getCitiesRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCitiesResponse", WrapperNamespace="http://booking/", IsWrapped=true)]
    public partial class getCitiesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://booking/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public TaxiClient.AttractionService.city[] @return;
        
        public getCitiesResponse() {
        }
        
        public getCitiesResponse(TaxiClient.AttractionService.city[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAttractions", WrapperNamespace="http://booking/", IsWrapped=true)]
    public partial class getAttractionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://booking/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://booking/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://booking/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://booking/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg3;
        
        public getAttractionsRequest() {
        }
        
        public getAttractionsRequest(string arg0, int arg1, int arg2, int arg3) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAttractionsResponse", WrapperNamespace="http://booking/", IsWrapped=true)]
    public partial class getAttractionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://booking/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public TaxiClient.AttractionService.attractie[] @return;
        
        public getAttractionsResponse() {
        }
        
        public getAttractionsResponse(TaxiClient.AttractionService.attractie[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="bookAttraction", WrapperNamespace="http://booking/", IsWrapped=true)]
    public partial class bookAttractionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://booking/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://booking/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("arg1", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public TaxiClient.AttractionService.orderedTicket[] arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://booking/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://booking/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg3;
        
        public bookAttractionRequest() {
        }
        
        public bookAttractionRequest(int arg0, TaxiClient.AttractionService.orderedTicket[] arg1, System.DateTime arg2, string arg3) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="bookAttractionResponse", WrapperNamespace="http://booking/", IsWrapped=true)]
    public partial class bookAttractionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://booking/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public bookAttractionResponse() {
        }
        
        public bookAttractionResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAttractionTypes", WrapperNamespace="http://booking/", IsWrapped=true)]
    public partial class getAttractionTypesRequest {
        
        public getAttractionTypesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAttractionTypesResponse", WrapperNamespace="http://booking/", IsWrapped=true)]
    public partial class getAttractionTypesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://booking/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public TaxiClient.AttractionService.attractieType[] @return;
        
        public getAttractionTypesResponse() {
        }
        
        public getAttractionTypesResponse(TaxiClient.AttractionService.attractieType[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AttractionImplementationChannel : TaxiClient.AttractionService.AttractionImplementation, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AttractionImplementationClient : System.ServiceModel.ClientBase<TaxiClient.AttractionService.AttractionImplementation>, TaxiClient.AttractionService.AttractionImplementation {
        
        public AttractionImplementationClient() {
        }
        
        public AttractionImplementationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AttractionImplementationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AttractionImplementationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AttractionImplementationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaxiClient.AttractionService.getCountriesResponse TaxiClient.AttractionService.AttractionImplementation.getCountries(TaxiClient.AttractionService.getCountriesRequest request) {
            return base.Channel.getCountries(request);
        }
        
        public TaxiClient.AttractionService.country[] getCountries() {
            TaxiClient.AttractionService.getCountriesRequest inValue = new TaxiClient.AttractionService.getCountriesRequest();
            TaxiClient.AttractionService.getCountriesResponse retVal = ((TaxiClient.AttractionService.AttractionImplementation)(this)).getCountries(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TaxiClient.AttractionService.getCountriesResponse> TaxiClient.AttractionService.AttractionImplementation.getCountriesAsync(TaxiClient.AttractionService.getCountriesRequest request) {
            return base.Channel.getCountriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<TaxiClient.AttractionService.getCountriesResponse> getCountriesAsync() {
            TaxiClient.AttractionService.getCountriesRequest inValue = new TaxiClient.AttractionService.getCountriesRequest();
            return ((TaxiClient.AttractionService.AttractionImplementation)(this)).getCountriesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaxiClient.AttractionService.getRegionsResponse TaxiClient.AttractionService.AttractionImplementation.getRegions(TaxiClient.AttractionService.getRegionsRequest request) {
            return base.Channel.getRegions(request);
        }
        
        public TaxiClient.AttractionService.region[] getRegions(string arg0) {
            TaxiClient.AttractionService.getRegionsRequest inValue = new TaxiClient.AttractionService.getRegionsRequest();
            inValue.arg0 = arg0;
            TaxiClient.AttractionService.getRegionsResponse retVal = ((TaxiClient.AttractionService.AttractionImplementation)(this)).getRegions(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TaxiClient.AttractionService.getRegionsResponse> TaxiClient.AttractionService.AttractionImplementation.getRegionsAsync(TaxiClient.AttractionService.getRegionsRequest request) {
            return base.Channel.getRegionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<TaxiClient.AttractionService.getRegionsResponse> getRegionsAsync(string arg0) {
            TaxiClient.AttractionService.getRegionsRequest inValue = new TaxiClient.AttractionService.getRegionsRequest();
            inValue.arg0 = arg0;
            return ((TaxiClient.AttractionService.AttractionImplementation)(this)).getRegionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaxiClient.AttractionService.getBookingResponse TaxiClient.AttractionService.AttractionImplementation.getBooking(TaxiClient.AttractionService.getBookingRequest request) {
            return base.Channel.getBooking(request);
        }
        
        public TaxiClient.AttractionService.booking[] getBooking(int arg0, string arg1) {
            TaxiClient.AttractionService.getBookingRequest inValue = new TaxiClient.AttractionService.getBookingRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            TaxiClient.AttractionService.getBookingResponse retVal = ((TaxiClient.AttractionService.AttractionImplementation)(this)).getBooking(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TaxiClient.AttractionService.getBookingResponse> TaxiClient.AttractionService.AttractionImplementation.getBookingAsync(TaxiClient.AttractionService.getBookingRequest request) {
            return base.Channel.getBookingAsync(request);
        }
        
        public System.Threading.Tasks.Task<TaxiClient.AttractionService.getBookingResponse> getBookingAsync(int arg0, string arg1) {
            TaxiClient.AttractionService.getBookingRequest inValue = new TaxiClient.AttractionService.getBookingRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((TaxiClient.AttractionService.AttractionImplementation)(this)).getBookingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaxiClient.AttractionService.getCitiesResponse TaxiClient.AttractionService.AttractionImplementation.getCities(TaxiClient.AttractionService.getCitiesRequest request) {
            return base.Channel.getCities(request);
        }
        
        public TaxiClient.AttractionService.city[] getCities(int arg0) {
            TaxiClient.AttractionService.getCitiesRequest inValue = new TaxiClient.AttractionService.getCitiesRequest();
            inValue.arg0 = arg0;
            TaxiClient.AttractionService.getCitiesResponse retVal = ((TaxiClient.AttractionService.AttractionImplementation)(this)).getCities(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TaxiClient.AttractionService.getCitiesResponse> TaxiClient.AttractionService.AttractionImplementation.getCitiesAsync(TaxiClient.AttractionService.getCitiesRequest request) {
            return base.Channel.getCitiesAsync(request);
        }
        
        public System.Threading.Tasks.Task<TaxiClient.AttractionService.getCitiesResponse> getCitiesAsync(int arg0) {
            TaxiClient.AttractionService.getCitiesRequest inValue = new TaxiClient.AttractionService.getCitiesRequest();
            inValue.arg0 = arg0;
            return ((TaxiClient.AttractionService.AttractionImplementation)(this)).getCitiesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaxiClient.AttractionService.getAttractionsResponse TaxiClient.AttractionService.AttractionImplementation.getAttractions(TaxiClient.AttractionService.getAttractionsRequest request) {
            return base.Channel.getAttractions(request);
        }
        
        public TaxiClient.AttractionService.attractie[] getAttractions(string arg0, int arg1, int arg2, int arg3) {
            TaxiClient.AttractionService.getAttractionsRequest inValue = new TaxiClient.AttractionService.getAttractionsRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            TaxiClient.AttractionService.getAttractionsResponse retVal = ((TaxiClient.AttractionService.AttractionImplementation)(this)).getAttractions(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TaxiClient.AttractionService.getAttractionsResponse> TaxiClient.AttractionService.AttractionImplementation.getAttractionsAsync(TaxiClient.AttractionService.getAttractionsRequest request) {
            return base.Channel.getAttractionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<TaxiClient.AttractionService.getAttractionsResponse> getAttractionsAsync(string arg0, int arg1, int arg2, int arg3) {
            TaxiClient.AttractionService.getAttractionsRequest inValue = new TaxiClient.AttractionService.getAttractionsRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            return ((TaxiClient.AttractionService.AttractionImplementation)(this)).getAttractionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaxiClient.AttractionService.bookAttractionResponse TaxiClient.AttractionService.AttractionImplementation.bookAttraction(TaxiClient.AttractionService.bookAttractionRequest request) {
            return base.Channel.bookAttraction(request);
        }
        
        public int bookAttraction(int arg0, TaxiClient.AttractionService.orderedTicket[] arg1, System.DateTime arg2, string arg3) {
            TaxiClient.AttractionService.bookAttractionRequest inValue = new TaxiClient.AttractionService.bookAttractionRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            TaxiClient.AttractionService.bookAttractionResponse retVal = ((TaxiClient.AttractionService.AttractionImplementation)(this)).bookAttraction(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TaxiClient.AttractionService.bookAttractionResponse> TaxiClient.AttractionService.AttractionImplementation.bookAttractionAsync(TaxiClient.AttractionService.bookAttractionRequest request) {
            return base.Channel.bookAttractionAsync(request);
        }
        
        public System.Threading.Tasks.Task<TaxiClient.AttractionService.bookAttractionResponse> bookAttractionAsync(int arg0, TaxiClient.AttractionService.orderedTicket[] arg1, System.DateTime arg2, string arg3) {
            TaxiClient.AttractionService.bookAttractionRequest inValue = new TaxiClient.AttractionService.bookAttractionRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            return ((TaxiClient.AttractionService.AttractionImplementation)(this)).bookAttractionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaxiClient.AttractionService.getAttractionTypesResponse TaxiClient.AttractionService.AttractionImplementation.getAttractionTypes(TaxiClient.AttractionService.getAttractionTypesRequest request) {
            return base.Channel.getAttractionTypes(request);
        }
        
        public TaxiClient.AttractionService.attractieType[] getAttractionTypes() {
            TaxiClient.AttractionService.getAttractionTypesRequest inValue = new TaxiClient.AttractionService.getAttractionTypesRequest();
            TaxiClient.AttractionService.getAttractionTypesResponse retVal = ((TaxiClient.AttractionService.AttractionImplementation)(this)).getAttractionTypes(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TaxiClient.AttractionService.getAttractionTypesResponse> TaxiClient.AttractionService.AttractionImplementation.getAttractionTypesAsync(TaxiClient.AttractionService.getAttractionTypesRequest request) {
            return base.Channel.getAttractionTypesAsync(request);
        }
        
        public System.Threading.Tasks.Task<TaxiClient.AttractionService.getAttractionTypesResponse> getAttractionTypesAsync() {
            TaxiClient.AttractionService.getAttractionTypesRequest inValue = new TaxiClient.AttractionService.getAttractionTypesRequest();
            return ((TaxiClient.AttractionService.AttractionImplementation)(this)).getAttractionTypesAsync(inValue);
        }
    }
}
