// <auto-generated />
namespace TaxiService.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class idweggehaald : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(idweggehaald));
        
        string IMigrationMetadata.Id
        {
            get { return "201306181300583_id weggehaald"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
