
package booking;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AttractionImplementationService", targetNamespace = "http://booking/", wsdlLocation = "file:/home/michael/git/THO8/AttractieService/src/conf/xml-resources/web-services/NewWebServiceFromWSDL/wsdl/AttractionService.wsdl")
public class AttractionImplementationService
    extends Service
{

    private final static URL ATTRACTIONIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException ATTRACTIONIMPLEMENTATIONSERVICE_EXCEPTION;
    private final static QName ATTRACTIONIMPLEMENTATIONSERVICE_QNAME = new QName("http://booking/", "AttractionImplementationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/michael/git/THO8/AttractieService/src/conf/xml-resources/web-services/NewWebServiceFromWSDL/wsdl/AttractionService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ATTRACTIONIMPLEMENTATIONSERVICE_WSDL_LOCATION = url;
        ATTRACTIONIMPLEMENTATIONSERVICE_EXCEPTION = e;
    }

    public AttractionImplementationService() {
        super(__getWsdlLocation(), ATTRACTIONIMPLEMENTATIONSERVICE_QNAME);
    }

    public AttractionImplementationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ATTRACTIONIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public AttractionImplementationService(URL wsdlLocation) {
        super(wsdlLocation, ATTRACTIONIMPLEMENTATIONSERVICE_QNAME);
    }

    public AttractionImplementationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ATTRACTIONIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public AttractionImplementationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AttractionImplementationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AttractionImplementation
     */
    @WebEndpoint(name = "AttractionImplementationPort")
    public AttractionImplementation getAttractionImplementationPort() {
        return super.getPort(new QName("http://booking/", "AttractionImplementationPort"), AttractionImplementation.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AttractionImplementation
     */
    @WebEndpoint(name = "AttractionImplementationPort")
    public AttractionImplementation getAttractionImplementationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://booking/", "AttractionImplementationPort"), AttractionImplementation.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ATTRACTIONIMPLEMENTATIONSERVICE_EXCEPTION!= null) {
            throw ATTRACTIONIMPLEMENTATIONSERVICE_EXCEPTION;
        }
        return ATTRACTIONIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    }

}
