
package flightservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import flightserviceDTO.ArrayOfAirportDTO;
import flightserviceDTO.ArrayOfBookingDTO;
import flightserviceDTO.ArrayOfFlightDTO;
import flightserviceDTO.ArrayOfPassengerDTO;
import flightserviceDTO.BookingDTO;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FlightService", targetNamespace = "http://flightservice.themaopdracht8.nl")
@XmlSeeAlso({
    serialization.ObjectFactory.class,
    flightservice.ObjectFactory.class,
    flightserviceDTO.ObjectFactory.class,
    system.ObjectFactory.class
})
public interface FlightService {


    /**
     * 
     * @param passengers
     * @param departureDate
     * @param destinationId
     * @param departureId
     * @return
     *     returns org.datacontract.schemas._2004._07.flightservice.ArrayOfFlightDTO
     * @throws FlightServiceShowFlightsByDepartureExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ShowFlightsByDeparture", action = "http://flightservice.themaopdracht8.nl/FlightService/ShowFlightsByDeparture")
    @WebResult(name = "ShowFlightsByDepartureResult", targetNamespace = "http://flightservice.themaopdracht8.nl")
    @RequestWrapper(localName = "ShowFlightsByDeparture", targetNamespace = "http://flightservice.themaopdracht8.nl", className = "nl.themaopdracht8.flightservice.ShowFlightsByDeparture")
    @ResponseWrapper(localName = "ShowFlightsByDepartureResponse", targetNamespace = "http://flightservice.themaopdracht8.nl", className = "nl.themaopdracht8.flightservice.ShowFlightsByDepartureResponse")
    public ArrayOfFlightDTO showFlightsByDeparture(
        @WebParam(name = "departureId", targetNamespace = "http://flightservice.themaopdracht8.nl")
        Integer departureId,
        @WebParam(name = "destinationId", targetNamespace = "http://flightservice.themaopdracht8.nl")
        Integer destinationId,
        @WebParam(name = "departureDate", targetNamespace = "http://flightservice.themaopdracht8.nl")
        XMLGregorianCalendar departureDate,
        @WebParam(name = "passengers", targetNamespace = "http://flightservice.themaopdracht8.nl")
        Integer passengers)
        throws FlightServiceShowFlightsByDepartureExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param passengers
     * @param destinationId
     * @param arrivalDate
     * @param departureId
     * @return
     *     returns org.datacontract.schemas._2004._07.flightservice.ArrayOfFlightDTO
     * @throws FlightServiceShowFlightsByArrivalExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ShowFlightsByArrival", action = "http://flightservice.themaopdracht8.nl/FlightService/ShowFlightsByArrival")
    @WebResult(name = "ShowFlightsByArrivalResult", targetNamespace = "http://flightservice.themaopdracht8.nl")
    @RequestWrapper(localName = "ShowFlightsByArrival", targetNamespace = "http://flightservice.themaopdracht8.nl", className = "nl.themaopdracht8.flightservice.ShowFlightsByArrival")
    @ResponseWrapper(localName = "ShowFlightsByArrivalResponse", targetNamespace = "http://flightservice.themaopdracht8.nl", className = "nl.themaopdracht8.flightservice.ShowFlightsByArrivalResponse")
    public ArrayOfFlightDTO showFlightsByArrival(
        @WebParam(name = "departureId", targetNamespace = "http://flightservice.themaopdracht8.nl")
        Integer departureId,
        @WebParam(name = "destinationId", targetNamespace = "http://flightservice.themaopdracht8.nl")
        Integer destinationId,
        @WebParam(name = "arrivalDate", targetNamespace = "http://flightservice.themaopdracht8.nl")
        XMLGregorianCalendar arrivalDate,
        @WebParam(name = "passengers", targetNamespace = "http://flightservice.themaopdracht8.nl")
        Integer passengers)
        throws FlightServiceShowFlightsByArrivalExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param searchValue
     * @return
     *     returns org.datacontract.schemas._2004._07.flightservice.ArrayOfAirportDTO
     * @throws FlightServiceGetAirportsExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetAirports", action = "http://flightservice.themaopdracht8.nl/FlightService/GetAirports")
    @WebResult(name = "GetAirportsResult", targetNamespace = "http://flightservice.themaopdracht8.nl")
    @RequestWrapper(localName = "GetAirports", targetNamespace = "http://flightservice.themaopdracht8.nl", className = "nl.themaopdracht8.flightservice.GetAirports")
    @ResponseWrapper(localName = "GetAirportsResponse", targetNamespace = "http://flightservice.themaopdracht8.nl", className = "nl.themaopdracht8.flightservice.GetAirportsResponse")
    public ArrayOfAirportDTO getAirports(
        @WebParam(name = "searchValue", targetNamespace = "http://flightservice.themaopdracht8.nl")
        String searchValue)
        throws FlightServiceGetAirportsExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param passengers
     * @param flightId
     * @param userToken
     * @return
     *     returns org.datacontract.schemas._2004._07.flightservice.BookingDTO
     * @throws FlightServiceBookFlightExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "BookFlight", action = "http://flightservice.themaopdracht8.nl/FlightService/BookFlight")
    @WebResult(name = "BookFlightResult", targetNamespace = "http://flightservice.themaopdracht8.nl")
    @RequestWrapper(localName = "BookFlight", targetNamespace = "http://flightservice.themaopdracht8.nl", className = "nl.themaopdracht8.flightservice.BookFlight")
    @ResponseWrapper(localName = "BookFlightResponse", targetNamespace = "http://flightservice.themaopdracht8.nl", className = "nl.themaopdracht8.flightservice.BookFlightResponse")
    public BookingDTO bookFlight(
        @WebParam(name = "flightId", targetNamespace = "http://flightservice.themaopdracht8.nl")
        Integer flightId,
        @WebParam(name = "passengers", targetNamespace = "http://flightservice.themaopdracht8.nl")
        ArrayOfPassengerDTO passengers,
        @WebParam(name = "userToken", targetNamespace = "http://flightservice.themaopdracht8.nl")
        String userToken)
        throws FlightServiceBookFlightExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param userToken
     * @return
     *     returns org.datacontract.schemas._2004._07.flightservice.ArrayOfBookingDTO
     * @throws FlightServiceGetPersonalBookingsExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetPersonalBookings", action = "http://flightservice.themaopdracht8.nl/FlightService/GetPersonalBookings")
    @WebResult(name = "GetPersonalBookingsResult", targetNamespace = "http://flightservice.themaopdracht8.nl")
    @RequestWrapper(localName = "GetPersonalBookings", targetNamespace = "http://flightservice.themaopdracht8.nl", className = "nl.themaopdracht8.flightservice.GetPersonalBookings")
    @ResponseWrapper(localName = "GetPersonalBookingsResponse", targetNamespace = "http://flightservice.themaopdracht8.nl", className = "nl.themaopdracht8.flightservice.GetPersonalBookingsResponse")
    public ArrayOfBookingDTO getPersonalBookings(
        @WebParam(name = "userToken", targetNamespace = "http://flightservice.themaopdracht8.nl")
        String userToken)
        throws FlightServiceGetPersonalBookingsExceptionFaultFaultMessage
    ;

}
