// <auto-generated />
namespace CarRentalService.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class IDontKnowIfIAddedSomething : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IDontKnowIfIAddedSomething));
        
        string IMigrationMetadata.Id
        {
            get { return "201306231804134_IDontKnowIfIAddedSomething"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
